// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywgqrutamfepvouflecp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Z3FydXRhbWZlcHZvdWZsZWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTIzMDksImV4cCI6MjA4OTA2ODMwOX0.M61XYyjYCUbO6cdu5iSlP-uJQMYONqio6mmwuvB7ZAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});