// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbpzgcikptjsngebval.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YnB6Z2Npa3B0anNuZ2VidmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MjI1NTEsImV4cCI6MjA4MTM5ODU1MX0.TZhpGG6hJlZsCYzO3oAX8NAUp4bCWqYPjGV_VR95Bn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});